apiVersion: v1
kind: PersistentVolume
metadata:
  name: metadata-mysql
  labels:
    type: local
    app: metadata
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/metadata
