apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-claim
  labels:
    type: local
    app: minio
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/minio
