apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-claim
  labels:
    type: local
    app: mysql
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mysql
